Map<String, List<String>> appLang = {
  'English': [
    'Theme', // 0
    'Light', // 1
    'Dark', // 2
    'System', // 3
    '10,000+ Views', // 4
    'Get thousands of views daily on your WhatsApp status in just few steps.', // 5
    'One Click', // 6
    'Follow the few steps to gain thousands of contacts in one click.', // 7
    'Perfect Audience', // 8
    'Sort contacts and audience according to countries and many more.', // 9
    'Submit Contact', // 10
    'Get Daily VCF', // 11
    'Telegram Channel', // 12
    'Rate us 5 Stars', // 13
    'Terms and Policy', // 14
    'Report Contact', // 15
    'Remove Contact', // 16
    'Go Premium', // 17
    'Language >>', // 18
    'Device:', // 19
    'Get Your WhatsApp Status Views Increased Daily', // 20
    'Submit Contact ______', // 21
    'Submit your WhatsApp number in order to be added to among those that will get VCF files on Wassapviews.', // 22
    'Submit Contact', // 23
    'Download VCF ______', // 24
    'You get your personal VCF file and import it directly to your phone. (Each user has a different VCF file)', // 25
    'Get VCF file', // 26
    'Submit your WhatsApp number below', // 27
    'Enter your name:', // 28
    'This field is required!', // 29
    'Submit', // 30
    'Wassapviews will never ask for sensitive information. Do not send passwords, money or any sensitive information to anyone you got from this app.', // 31
    'Report contacts below', // 32
    'Enter the Contact you want to report and give your reason for reporting.', // 33
    'Remove your WhatsApp number below', // 34
    'Get your VCF files here daily', // 35
    'Enter Number:', // 36
    'Note: You need to download VCF files everyday.', // 37
    'Remove Ads', // 38
    'Premium Plan', // 39
    'Select your plan below', // 40
    'Monthly Plan', // 41
    'Yearly Plan', // 42
    'PROFILE DETAILS', // 43
  ],
  'Chinese': [
    '主题',
    '光',
    '黑暗的',
    '系统',
    '10,000+ 次观看',
    '只需几个步骤，您的 WhatsApp 状态每天就能获得数以千计的浏览量。',
    '一键',
    '按照几个步骤，一键获取数千个联系人。',
    '完美的观众',
    '根据国家等对联系人和受众进行排序。',
    '提交联系方式',
    '获取 VCF',
    '电报频道',
    '给我们评分 5 星',
    '条款和政策',
    '举报联系人',
    '删除联系人',
    '高级版',
    '语言 >>',
    '设备：',
    '让您的 WhatsApp 状态视图每天增加',
    '提交联系人______',
    '提交您的 WhatsApp 号码，以便添加到将在 Wassapviews 上获取 VCF 文件的号码中。',
    '提交联系方式',
    '下载 VCF ______',
    '您可以获得您的个人 VCF 文件并将其直接导入到您的手机中。 （每个用户有不同的 VCF 文件）',
    '获取 VCF 文件',
    '在下方提交您的 WhatsApp 号码',
    '输入你的名字：',
    '这是必填栏！',
    '提交',
    'Wassapviews 永远不会询问敏感信息。不要将密码、金钱或任何敏感信息发送给您从此应用程序获得的任何人。',
    '在下方报告联系人',
    '输入您要举报的联系人并说明您举报的原因。',
    '在下方删除您的 WhatsApp 号码',
    '每天在这里获取您的 VCF 文件',
    '输入号码：',
    '注意：您需要每天下载 VCF 文件。',
    '移除广告',
    '高级计划',
    '在下面选择您的计划',
    '月度计划',
    '年度计划',
    '资料详情',
  ],
  'Spanish': [
    'Tema',
    'Ligera',
    'Oscura',
    'Sistema',
    '10,000+ Vistas',
    'Obtenga miles de vistas diarias sobre su estado de WhatsApp en solo unos pocos pasos.',
    'Un click',
    'Siga los pocos pasos para obtener miles de contactos con un solo clic.',
    'Audiencia perfecta',
    'Ordene los contactos y la audiencia según los países y muchos más.',
    'Enviar contacto',
    'Obtener VCF',
    'Canal de Telegram',
    'Califícanos 5 estrellas',
    'Condiciones y política',
    'Informar de contacto',
    'Remover contacto',
    'Hazte Premium',
    'Idioma >>',
    'Dispositivo:',
    'Obtenga sus vistas de estado de WhatsApp aumentadas diariamente',
    'Enviar contacto ______',
    'Envíe su número de WhatsApp para que se le agregue entre los que recibirán archivos VCF en Wassapviews.',
    'Enviar contacto',
    'Descarga VCF ______',
    'Obtiene su archivo VCF personal y lo importa directamente a su teléfono. (Cada usuario tiene un archivo VCF diferente)',
    'Obtener el archivo VCF',
    'Envíe su número de WhatsApp a continuación',
    'Introduzca su nombre:',
    '¡Este campo es obligatorio!',
    'Entregar',
    'Wassapviews nunca solicitará información confidencial. No envíe contraseñas, dinero ni información confidencial a nadie que haya obtenido de esta aplicación.',
    'Informar de los contactos a continuación',
    'Ingrese el contacto que desea denunciar y proporcione el motivo de la denuncia.',
    'Elimina tu número de WhatsApp a continuación',
    'Obtenga sus archivos VCF aquí todos los días',
    'Ingresar número:',
    'Nota: debe descargar archivos VCF todos los días.',
    'Quitar anuncios',
    'Plan Premium',
    'Seleccione su plan a continuación',
    'Plan mensual',
    'Plan Anual',
    'DETALLES DEL PERFIL',
  ],
  'Hindi': [
    'विषय',
    'रोशनी',
    'अंधेरा',
    'प्रणाली',
    '10,000+ दृश्य',
    'अपने WhatsApp स्टेटस पर कुछ ही चरणों में प्रतिदिन हज़ारों बार देखे जाने की संख्या प्राप्त करें।',
    'एक बार दबाओ',
    'एक क्लिक में हजारों संपर्क हासिल करने के लिए कुछ चरणों का पालन करें।',
    'सही दर्शक',
    'देशों और कई अन्य के अनुसार संपर्कों और दर्शकों को क्रमबद्ध करें।',
    'संपर्क जमा करें',
    'वीसीएफ प्राप्त करें',
    'टेलीग्राम चैनल',
    'हमें 5 स्टार रेट करें',
    'नियम और नीति',
    'रिपोर्ट संपर्क',
    'संपर्क हटाएं',
    'प्रीमियम के लिए जाएँ',
    'भाषा >>',
    'डिवाइस:',
    'अपने व्हाट्सएप स्टेटस व्यूज को रोजाना बढ़ाएं',
    'संपर्क जमा करें ______',
    'उन लोगों में जोड़ने के लिए अपना व्हाट्सएप नंबर जमा करें, जिन्हें वासेपगेन्स पर वीसीएफ फाइलें मिलेंगी।',
    'संपर्क जमा करें',
    'वीसीएफ ______ डाउनलोड करें',
    'आप अपनी व्यक्तिगत वीसीएफ फाइल प्राप्त करते हैं और इसे सीधे अपने फोन पर आयात करते हैं। (प्रत्येक उपयोगकर्ता के पास एक अलग VCF फ़ाइल होती है)',
    'वीसीएफ फ़ाइल प्राप्त करें',
    'अपना व्हाट्सएप नंबर नीचे सबमिट करें',
    'अपना नाम दर्ज करें:',
    'यह फ़ील्ड आवश्यक है!',
    'प्रस्तुत करना',
    'Wassapviews कभी भी संवेदनशील जानकारी नहीं मांगेगा। इस ऐप से आपको पासवर्ड, पैसा या कोई भी संवेदनशील जानकारी किसी को न भेजें।',
    'नीचे संपर्कों की रिपोर्ट करें',
    'वह संपर्क दर्ज करें जिसकी आप रिपोर्ट करना चाहते हैं और रिपोर्टिंग के लिए अपना कारण दें।',
    'अपना व्हाट्सएप नंबर नीचे हटाएं',
    'अपनी वीसीएफ फाइलें यहां प्रतिदिन प्राप्त करें',
    'नंबर डालें:',
    'नोट: आपको प्रतिदिन वीसीएफ फाइलें डाउनलोड करनी होंगी।',
    'विज्ञापन हटाएँ',
    'प्रीमियम योजना',
    'नीचे अपनी योजना चुनें',
    'मासिक योजना',
    'वार्षिक योजना',
    'प्रोफ़ाइल विवरण',
  ],
  'Arabic': [
    'سمة',
    'خفيفة',
    'داكن',
    'نظام',
    '10،000+ مشاهدة',
    'احصل على آلاف المشاهدات يوميًا لحالة WhatsApp الخاصة بك في خطوات قليلة فقط.',
    'نقره واحدة',
    'اتبع الخطوات القليلة للحصول على آلاف جهات الاتصال بنقرة واحدة.',
    'جمهور مثالي',
    'فرز جهات الاتصال والجمهور وفقًا للبلدان وغيرها الكثير.',
    'إرسال جهة الاتصال',
    'احصل على VCF',
    'قناة برقية',
    'قيمنا 5 نجوم',
    'الشروط والسياسة',
    'إبلاغ عن جهة اتصال',
    'ازالة بيانات الاتصال بالشخص',
    'احصل على الاشتراك الرئيسي',
    'اللغة >>',
    'جهاز:',
    'احصل على مشاهدات حالة WhatsApp الخاصة بك بشكل متزايد يوميًا',
    'إرسال جهة الاتصال ______',
    'أرسل رقم WhatsApp الخاص بك لتتم إضافته من بين أولئك الذين سيحصلون على ملفات VCF على Wassapviews.',
    'إرسال جهة الاتصال',
    'تنزيل VCF ______',
    'تحصل على ملف VCF الشخصي الخاص بك وتستورده مباشرة إلى هاتفك. (كل مستخدم لديه ملف VCF مختلف)',
    'احصل على ملف VCF',
    'أرسل رقم WhatsApp الخاص بك أدناه',
    'أدخل أسمك:',
    'هذه الخانة مطلوبه!',
    'إرسال',
    'لن تطلب Wassapviews أبدًا معلومات حساسة. لا ترسل كلمات مرور أو أموالاً أو أي معلومات حساسة لأي شخص تحصل عليه من هذا التطبيق.',
    'الإبلاغ عن جهات الاتصال أدناه',
    'أدخل جهة الاتصال التي تريد الإبلاغ عنها وضح سبب الإبلاغ.',
    'قم بإزالة رقم WhatsApp الخاص بك أدناه',
    'احصل على ملفات VCF هنا يوميًا',
    'أدخل رقم:',
    'ملاحظة: أنت بحاجة إلى تنزيل ملفات VCF كل يوم.',
    'ازالة الاعلانات',
    'خطة بريميوم',
    'حدد خطتك أدناه',
    'خطة شهرية',
    'الخطة السنوية',
    'تفاصيل الملف الشخصي',
  ],
  'Portuguese': [
    'Tema',
    'Leve',
    'Escura',
    'Sistema',
    'Mais de 10.000 visualizações',
    'Obtenha milhares de visualizações diárias sobre o status do seu WhatsApp em apenas algumas etapas.',
    'Um clique',
    'Siga os poucos passos para ganhar milhares de contatos em um clique.',
    'Público Perfeito',
    'Classifique os contatos e o público de acordo com os países e muito mais.',
    'Enviar contato',
    'Obtenha VCF',
    'Canal Telegram',
    'Avalie-nos com 5 estrelas',
    'Termos e Política',
    'Reportar contato',
    'Remover contato',
    'Go Premium',
    'Linguagem >>',
    'Dispositivo:',
    'Aumente diariamente as visualizações do seu status do WhatsApp',
    'Enviar contato ______',
    'Envie seu número do WhatsApp para ser adicionado entre aqueles que obterão arquivos VCF no Wassapviews.',
    'Enviar contato',
    'Baixar VCF ______',
    'Você obtém seu arquivo VCF pessoal e o importa diretamente para o seu telefone. (Cada usuário tem um arquivo VCF diferente)',
    'Obter arquivo VCF',
    'Envie seu número do WhatsApp abaixo',
    'Digite seu nome:',
    'Este campo é obrigatório!',
    'Enviar',
    'Wassapviews nunca pedirá informações confidenciais. Não envie senhas, dinheiro ou qualquer informação sensível para ninguém que você obteve com este aplicativo.',
    'Reportar contatos abaixo',
    'Insira o contato que deseja denunciar e forneça o motivo da denúncia.',
    'Remova seu número do WhatsApp abaixo',
    'Obtenha seus arquivos VCF aqui diariamente',
    'Insira numeros:',
    'Nota: você precisa baixar arquivos VCF todos os dias.',
    'Remover propagandas',
    'Plano Premium',
    'Selecione seu plano abaixo',
    'Plano mensal',
    'Plano anual',
    'DETALHES DE PERFIL',
  ],
  'Russian': [
    'Тема',
    'Светлый',
    'Темно',
    'Система',
    '10,000+ просмотров',
    'Ежедневно получайте тысячи просмотров своего статуса в WhatsApp всего за несколько шагов.',
    'Один клик',
    'Выполните несколько шагов, чтобы получить тысячи контактов одним щелчком мыши.',
    'Идеальная аудитория',
    'Сортируйте контакты и аудиторию по странам и многому другому.',
    'Отправить контакт',
    'Получить VCF',
    'Телеграмм канал',
    'Оцените нас на 5 звезд',
    'Условия и политика',
    'Сообщить о контакте',
    'Удалить контакт',
    'Перейти Премиум',
    'Язык >>',
    'Устройство:',
    'Увеличивайте количество просмотров статуса WhatsApp с каждым днем',
    'Отправить контакт ______',
    'Укажите свой номер WhatsApp, чтобы его добавили к тем, кто получит файлы VCF на Wassapviews.',
    'Отправить контакт',
    'Скачать VCF ______',
    'Вы получаете свой личный файл VCF и импортируете его прямо на свой телефон. (У каждого пользователя свой файл VCF)',
    'Получить файл VCF',
    'Укажите свой номер WhatsApp ниже',
    'Введите ваше имя:',
    'Это поле обязательно к заполнению!',
    'Представлять на рассмотрение',
    'Wassapviews никогда не запрашивает конфиденциальную информацию. Не отправляйте никому пароли, деньги или какую-либо конфиденциальную информацию, полученную с помощью этого приложения.',
    'Сообщите о контактах ниже',
    'Введите контакт, о котором вы хотите сообщить, и укажите причину сообщения.',
    'Удалите свой номер WhatsApp ниже',
    'Ежедневно загружайте сюда свои файлы VCF',
    'Введите номер:',
    'Примечание. Вам необходимо загружать файлы VCF каждый день.',
    'Удалить рекламу',
    'Премиум план',
    'Выберите свой план ниже',
    'Ежемесячный план',
    'Годовой план',
    'ДЕТАЛИ ПРОФИЛЯ',
  ],
  'Japanese': [
    'テーマ',
    '光',
    '闇',
    'システム',
    '10,000回以上の視聴',
    'ほんの数ステップで、WhatsAppステータスの数千のビューを毎日取得できます。',
    'ワンクリック',
    'いくつかの手順に従って、ワンクリックで数千の連絡先を取得します。',
    '完璧なオーディエンス',
    '国などに応じて連絡先とオーディエンスを並べ替えます。',
    '連絡先を送信',
    'VCFを入手する',
    'テレグラムチャネル',
    '5つ星を評価してください',
    '利用規約とポリシー',
    '連絡先の報告',
    '連絡先を削除します',
    'プレミアムに行く',
    '言語>>',
    '端末：',
    'WhatsAppステータスビューを毎日増やしましょう',
    '連絡先の送信______',
    'WassapviewsでVCFファイルを取得するものに追加するには、WhatsApp番号を送信してください。',
    '連絡先を送信',
    'VCFをダウンロード______',
    '個人のVCFファイルを取得し、それを電話に直接インポートします。 （各ユーザーは異なるVCFファイルを持っています）',
    'VCFファイルを取得する',
    '以下にWhatsApp番号を送信してください',
    'あなたの名前を入力してください：',
    'この項目は必須です！',
    '送信',
    'Wassapviewsは機密情報を要求することはありません。このアプリから入手した人にパスワード、お金、または機密情報を送信しないでください。',
    '以下の連絡先を報告してください',
    '報告する連絡先を入力し、報告する理由を説明してください。',
    '以下のWhatsApp番号を削除してください',
    'ここで毎日VCFファイルを入手してください',
    '番号を入力してください：',
    '注：VCFファイルは毎日ダウンロードする必要があります。',
    '広告を削除',
    'プレミアムプラン',
    '以下からプランを選択してください',
    '月額プラン',
    '年間計画',
    'プロファイルの詳細',
  ],
  'German': [
    'Thema',
    'Hell',
    'Dunkel',
    'System',
    '10.000+ Aufrufe',
    'Erhalten Sie in nur wenigen Schritten täglich Tausende von Ansichten Ihres WhatsApp-Status.',
    'Ein Klick',
    'Befolgen Sie die wenigen Schritte, um mit einem Klick Tausende von Kontakten zu gewinnen.',
    'Perfektes Publikum',
    'Sortieren Sie Kontakte und Zielgruppen nach Ländern und vielem mehr.',
    'Kontakt senden',
    'Holen Sie sich VCF',
    'Telegrammkanal',
    'Bewerten Sie uns mit 5 Sternen',
    'Bedingungen und Richtlinien',
    'Kontakt melden',
    'Kontakt entfernen',
    'Gehen Sie Premium',
    'Sprache >>',
    'Gerät:',
    'Holen Sie sich täglich mehr WhatsApp-Statusansichten',
    'Kontakt senden ______',
    'Senden Sie Ihre WhatsApp-Nummer, um zu denen hinzugefügt zu werden, die VCF-Dateien auf Wassapviews erhalten.',
    'Kontakt senden',
    'VCF herunterladen ______',
    'Sie erhalten Ihre persönliche VCF-Datei und importieren diese direkt auf Ihr Telefon. (Jeder Benutzer hat eine andere VCF-Datei)',
    'VCF-Datei abrufen',
    'Senden Sie Ihre WhatsApp-Nummer unten',
    'Gib deinen Namen ein:',
    'Dieses Feld ist erforderlich!',
    'einreichen',
    'Wassapviews wird niemals nach sensiblen Informationen fragen. Senden Sie keine Passwörter, Geld oder sensible Informationen an jemanden, den Sie von dieser App erhalten haben.',
    'Kontakte unten melden',
    'Geben Sie den Kontakt ein, den Sie melden möchten, und geben Sie Ihren Grund für die Meldung an.',
    'Entfernen Sie unten Ihre WhatsApp-Nummer',
    'Holen Sie sich hier täglich Ihre VCF-Dateien',
    'Nummer eingeben:',
    'Hinweis: Sie müssen täglich VCF-Dateien herunterladen.',
    'Anzeigen entfernen',
    'Premium-Plan',
    'Wählen Sie unten Ihren Plan aus',
    'Monatlicher Plan',
    'Jahresplan',
    'PROFILDETAILS',
  ],
  'Korean': [
    '주제',
    '빛',
    '어두운',
    '체계',
    '10,000개 이상의 조회수',
    '몇 단계만 거치면 WhatsApp 상태에 대해 매일 수천 개의 조회수를 얻을 수 있습니다.',
    '원 클릭',
    '한 번의 클릭으로 수천 개의 연락처를 얻으려면 몇 가지 단계를 따르십시오.',
    '완벽한 청중',
    '국가 등에 따라 연락처와 청중을 정렬합니다.',
    '연락처 제출',
    'VCF 가져오기',
    '텔레그램 채널',
    '평가 별 5개',
    '약관 및 정책',
    '연락처 보고',
    '연락처 삭제',
    '프리미엄으로 이동',
    '언어 >>',
    '장치:',
    'WhatsApp 상태 보기를 매일 증가시키십시오',
    '연락처 제출 ______',
    'WhatsApp 번호를 제출하면 Wassapviews에서 VCF 파일을 받을 수 있는 항목에 추가됩니다.',
    '연락처 제출',
    'VCF 다운로드 ______',
    '개인 VCF 파일을 가져와 휴대폰으로 직접 가져옵니다. (사용자마다 VCF 파일이 다릅니다)',
    'VCF 파일 가져오기',
    '아래 WhatsApp 번호를 제출하십시오',
    '당신의 이름을 입력:',
    '이 필드는 필수입니다!',
    '제출하다',
    'Wassapviews는 민감한 정보를 절대 요구하지 않습니다. 이 앱에서 얻은 누구에게도 비밀번호, 돈 또는 민감한 정보를 보내지 마십시오.',
    '아래 연락처 신고',
    '신고할 연락처를 입력하고 신고 사유를 입력합니다.',
    '아래 WhatsApp 번호를 제거하십시오.',
    '여기에서 매일 VCF 파일을 받으세요',
    '번호 입력:',
    '참고: 매일 VCF 파일을 다운로드해야 합니다.',
    '광고를 제거하다',
    '프리미엄 플랜',
    '아래에서 플랜을 선택하세요',
    '월간 요금제',
    '연간 계획',
    '프로필 세부정보',
  ],
  'French': [
    'Thème',
    'Lumière',
    'Foncée',
    'Système',
    'Plus de 10 000 vues',
    'Obtenez des milliers de vues par jour sur votre statut WhatsApp en quelques étapes seulement.',
    'Un clic',
    'Suivez les quelques étapes pour gagner des milliers de contacts en un clic.',
    'Public parfait',
    'Triez les contacts et l\'audience selon les pays et bien d\'autres.',
    'Soumettre Contact',
    'Obtenir le VCF',
    'Chaîne de télégramme',
    'Donnez-nous 5 étoiles',
    'Conditions et politique',
    'Signaler un contact',
    'Supprimer contact',
    'Passer en Premium',
    'Langue >>',
    'Appareil:',
    'Obtenez vos vues de statut WhatsApp augmentées quotidiennement',
    'Soumettre Contact ______',
    'Soumettez votre numéro WhatsApp afin d\'être ajouté à ceux qui obtiendront les fichiers VCF sur Wassapviews.',
    'Soumettre Contact',
    'Télécharger le VCF ______',
    'Vous obtenez votre fichier VCF personnel et l\'importez directement sur votre téléphone. (Chaque utilisateur a un fichier VCF différent)',
    'Obtenir le fichier VCF',
    'Soumettez votre numéro WhatsApp ci-dessous',
    'Entrez votre nom:',
    'Ce champ est requis!',
    'Soumettre',
    'Wassapviews ne demandera jamais d\'informations sensibles. N\'envoyez pas de mots de passe, d\'argent ou d\'informations sensibles à quiconque que vous avez obtenu à partir de cette application.',
    'Signaler les contacts ci-dessous',
    'Entrez le contact que vous souhaitez signaler et donnez la raison de votre signalement.',
    'Supprimez votre numéro WhatsApp ci-dessous',
    'Obtenez vos fichiers VCF ici quotidiennement',
    'Entrer un nombre:',
    'Remarque : vous devez télécharger les fichiers VCF tous les jours.',
    'Supprimez la pub',
    'Forfait Premium',
    'Sélectionnez votre forfait ci-dessous',
    'Plan mensuel',
    'Plan annuel',
    'DÉTAILS DU PROFIL',
  ],
  'Turkish': [
    'Tema',
    'Işık',
    'Karanlık',
    'sistem',
    '10.000+ Görüntüleme',
    'Sadece birkaç adımda WhatsApp durumunuzda her gün binlerce görüntü elde edin.',
    'Tek tık',
    'Tek bir tıklamayla binlerce kişi kazanmak için birkaç adımı izleyin.',
    'Mükemmel İzleyici',
    'Kişileri ve hedef kitleyi ülkelere ve daha fazlasına göre sıralayın.',
    'İletişim Gönder',
    'VCF alın',
    'Telgraf Kanalı',
    'Bize 5 Yıldız Ver',
    'Şartlar ve Politika',
    'Kişiyi Bildir',
    'Kişiyi kaldırmak',
    'Premium\'a geç',
    'Dil >>',
    'Cihaz:',
    'WhatsApp Durum Görüntülemelerinizi Günlük Arttırın',
    'Kişiyi Gönder ______',
    'Wassapviews\'de VCF dosyaları alacaklar arasına eklenmek için WhatsApp numaranızı gönderin.',
    'İletişim Gönder',
    'VCF\'yi indirin ______',
    'Kişisel VCF dosyanızı alır ve doğrudan telefonunuza aktarırsınız. (Her kullanıcının farklı bir VCF dosyası vardır)',
    'VCF dosyasını alın',
    'WhatsApp numaranızı aşağıya gönderin',
    'Adınızı giriniz:',
    'Bu alan gereklidir!',
    'Göndermek',
    'Wassapviews asla hassas bilgiler istemez. Bu uygulamadan edindiğiniz kimseye şifre, para veya herhangi bir hassas bilgi göndermeyin.',
    'Aşağıdaki kişileri bildir',
    'Şikayet etmek istediğiniz Kişiyi girin ve bildirme nedeninizi belirtin.',
    'Aşağıdaki WhatsApp numaranızı kaldırın',
    'VCF dosyalarınızı günlük olarak buradan alın',
    'Numarayı Girin:',
    'Not: Her gün VCF dosyalarını indirmeniz gerekir.',
    'reklamları kaldırmak',
    'Premium Plan',
    'Aşağıdan planınızı seçin',
    'Aylık plan',
    'Yıllık Plan',
    'PROFİL DETAYLARI',
  ],
  'Tamil': [
    'தீம்',
    'ஒளி',
    'இருள்',
    'அமைப்பு',
    '10,000+ பார்வைகள்',
    'சில படிகளில் உங்கள் வாட்ஸ்அப் நிலையை தினமும் ஆயிரக்கணக்கான பார்வைகளைப் பெறுங்கள்.',
    'ஒரு கிளிக்',
    'ஒரே கிளிக்கில் ஆயிரக்கணக்கான தொடர்புகளைப் பெற சில படிகளைப் பின்பற்றவும்.',
    'சரியான பார்வையாளர்கள்',
    'தொடர்புகள் மற்றும் பார்வையாளர்களை நாடுகள் மற்றும் பலவற்றின் படி வரிசைப்படுத்தவும்.',
    'தொடர்பைச் சமர்ப்பிக்கவும்',
    'VCF பெறவும்',
    'டெலிகிராம் சேனல்',
    'எங்களுக்கு 5 நட்சத்திரங்கள் என மதிப்பிடவும்',
    'விதிமுறைகள் மற்றும் கொள்கை',
    'தொடர்பைப் புகாரளிக்கவும்',
    'தொடர்பு நீக்க',
    'பிரீமியம் செல்லுங்கள்',
    'மொழி >>',
    'சாதனம்:',
    'உங்கள் வாட்ஸ்அப் ஸ்டேட்டஸ் பார்வைகளை தினசரி அதிகரித்துக் கொள்ளுங்கள்',
    'தொடர்பைச் சமர்ப்பிக்கவும் ______',
    'Wassapviews இல் VCF கோப்புகளைப் பெறுபவர்களில் சேர்க்க உங்கள் WhatsApp எண்ணைச் சமர்ப்பிக்கவும்.',
    'தொடர்பைச் சமர்ப்பிக்கவும்',
    'விசிஎஃப் பதிவிறக்கம் ______',
    'உங்கள் தனிப்பட்ட VCF கோப்பைப் பெற்று, அதை நேரடியாக உங்கள் தொலைபேசியில் இறக்குமதி செய்கிறீர்கள். (ஒவ்வொரு பயனருக்கும் வெவ்வேறு VCF கோப்பு உள்ளது)',
    'VCF கோப்பைப் பெறுங்கள்',
    'உங்கள் வாட்ஸ்அப் எண்ணை கீழே சமர்ப்பிக்கவும்',
    'உங்கள் பெயரை உள்ளிடவும்:',
    'இந்த புலம் தேவை!',
    'சமர்ப்பிக்கவும்',
    'Wassapviews ஒருபோதும் முக்கியமான தகவல்களைக் கேட்காது. இந்த பயன்பாட்டிலிருந்து நீங்கள் பெற்ற யாருக்கும் கடவுச்சொற்கள், பணம் அல்லது எந்த முக்கியத் தகவலையும் அனுப்ப வேண்டாம்.',
    'தொடர்புகளை கீழே புகாரளிக்கவும்',
    'நீங்கள் புகாரளிக்க விரும்பும் தொடர்பை உள்ளிட்டு, புகாரளிப்பதற்கான காரணத்தைக் குறிப்பிடவும்.',
    'கீழே உள்ள உங்கள் WhatsApp எண்ணை அகற்றவும்',
    'உங்கள் VCF கோப்புகளை தினமும் இங்கே பெறுங்கள்',
    'எண்ணை உள்ளிடவும்:',
    'குறிப்பு: நீங்கள் தினமும் VCF கோப்புகளை பதிவிறக்கம் செய்ய வேண்டும்.',
    'விளம்பரங்களை அகற்று',
    'பிரீமியம் திட்டம்',
    'கீழே உங்கள் திட்டத்தைத் தேர்ந்தெடுக்கவும்',
    'மாதாந்திர திட்டம்',
    'வருடாந்திர திட்டம்',
    'சுயவிவர விவரங்கள்',
  ],
  'Vietnamese': [
    'Chủ đề',
    'Nhẹ',
    'Tối tăm',
    'Hệ thống',
    'Hơn 10.000 lượt xem',
    'Nhận hàng nghìn lượt xem hàng ngày trên trạng thái WhatsApp của bạn chỉ trong vài bước.',
    'Một cú nhấp chuột',
    'Làm theo vài bước để có được hàng nghìn địa chỉ liên hệ chỉ trong một cú nhấp chuột.',
    'Đối tượng hoàn hảo',
    'Sắp xếp địa chỉ liên hệ và đối tượng theo quốc gia và nhiều hơn nữa.',
    'Gửi liên hệ',
    'Nhận VCF',
    'Kênh Telegram',
    'Đánh giá chúng tôi 5 sao',
    'Điều khoản và Chính sách',
    'Báo cáo liên hệ',
    'Xóa liên hệ',
    'Lên cao cấp',
    'Ngôn ngữ >>',
    'Thiết bị:',
    'Nhận số lượt xem trạng thái WhatsApp của bạn tăng lên hàng ngày',
    'Gửi liên hệ ______',
    'Gửi số WhatsApp của bạn để được thêm vào trong số những người sẽ nhận được tệp VCF trên Wassapviews.',
    'Gửi liên hệ',
    'Tải xuống VCF ______',
    'Bạn lấy tệp VCF cá nhân của mình và nhập trực tiếp vào điện thoại của bạn. (Mỗi người dùng có một tệp VCF khác nhau)',
    'Nhận tệp VCF',
    'Gửi số WhatsApp của bạn bên dưới',
    'Điền tên của bạn:',
    'Trường này là bắt buộc!',
    'Nộp',
    'Wassapviews sẽ không bao giờ hỏi thông tin nhạy cảm. Không gửi mật khẩu, tiền hoặc bất kỳ thông tin nhạy cảm nào cho bất kỳ ai bạn nhận được từ ứng dụng này.',
    'Báo cáo địa chỉ liên hệ bên dưới',
    'Nhập Địa chỉ liên hệ bạn muốn báo cáo và đưa ra lý do báo cáo.',
    'Xóa số WhatsApp của bạn bên dưới',
    'Nhận các tệp VCF của bạn ở đây hàng ngày',
    'Nhập số:',
    'Lưu ý: Bạn cần tải xuống các tệp VCF hàng ngày.',
    'Loại bỏ các quảng cáo',
    'Gói cao cấp',
    'Chọn kế hoạch của bạn bên dưới',
    'Kế hoạch hàng tháng',
    'Kế hoạch hằng năm',
    'CHI TIẾT HỒ SƠ',
  ],
  'Urdu': [
    'خیالیہ',
    'روشنی',
    'اندھیرا',
    'سسٹم',
    '10,000+ ملاحظات',
    'صرف چند قدموں میں اپنے WhatsApp اسٹیٹس پر روزانہ ہزاروں آراء حاصل کریں۔',
    'ایک کلک',
    'ایک کلک میں ہزاروں رابطے حاصل کرنے کے لیے چند مراحل پر عمل کریں۔',
    'کامل سامعین',
    'رابطوں اور سامعین کو ممالک اور بہت کچھ کے مطابق ترتیب دیں۔',
    'رابطہ جمع کروائیں۔',
    'VCF حاصل کریں۔',
    'ٹیلیگرام چینل',
    'ہمیں 5 ستاروں کی درجہ بندی کریں۔',
    'شرائط اور پالیسی',
    'رابطہ کی اطلاع دیں۔',
    'رابطہ کو ہٹا دیں۔',
    'پریمیم جاؤ',
    'زبان >>',
    'ڈیوائس:',
    'اپنے واٹس ایپ اسٹیٹس ویوز میں روزانہ اضافہ کریں۔',
    'رابطہ جمع کروائیں ______',
    'اپنا واٹس ایپ نمبر جمع کروائیں تاکہ ان لوگوں میں شامل کیا جا سکے جنہیں Wassapviews پر VCF فائلیں ملیں گی۔',
    'رابطہ جمع کروائیں۔',
    'VCF ڈاؤن لوڈ کریں ______',
    'آپ اپنی ذاتی VCF فائل حاصل کرتے ہیں اور اسے براہ راست اپنے فون پر درآمد کرتے ہیں۔ (ہر صارف کی مختلف VCF فائل ہوتی ہے)',
    'VCF فائل حاصل کریں۔',
    'نیچے اپنا واٹس ایپ نمبر بھیجیں۔',
    'اپنا نام درج کریں:',
    'اس کو پر کرنا ضروری ہے!',
    'جمع کرائیں',
    'Wassapviews کبھی بھی حساس معلومات نہیں مانگیں گے۔ اس ایپ سے جو بھی آپ کو ملا ہے اسے پاس ورڈ، رقم یا کوئی بھی حساس معلومات نہ بھیجیں۔',
    'ذیل میں رابطوں کی اطلاع دیں۔',
    'جس رابطہ کی آپ رپورٹ کرنا چاہتے ہیں اسے درج کریں اور رپورٹ کرنے کی وجہ بتائیں۔',
    'نیچے اپنا واٹس ایپ نمبر ہٹا دیں۔',
    'اپنی VCF فائلیں روزانہ یہاں حاصل کریں۔',
    'نمبر درج کریں:',
    'نوٹ: آپ کو روزانہ VCF فائلیں ڈاؤن لوڈ کرنے کی ضرورت ہے۔',
    'اشتہارات کو ہٹا دیں۔',
    'پریمیم پلان',
    'ذیل میں اپنا منصوبہ منتخب کریں۔',
    'ماہانہ منصوبہ',
    'سالانہ منصوبہ',
    'پروفائل کی تفصیلات',
  ],
};
